### PR TITLE
Feature/qr code scanner

### PR DESCRIPTION
**Pull request by Royd54**
As an user I want to scan QR codes so I can play one of the minigames and get the collectable. Open unity, go to build settings and build and run it on your phone to test. P.S. you need to connect your phone to your pc and need to accept notifications. After accepting restart the app and test the prototype. (keep in mind that your phone needs to be in developer mode)

### CODE REVIEW

**Review by TimoBrandt1 — APPROVED** [review]
My review is without opening the branch in untiy. The code is correct regarding the code guideliness. I did not persive any part of the code out of the ordinairy. By saying this I aprove this pull request.

**Comment by Stanley-Dam** [comment]
QRScanHandler is missing references.

**Comment by Stanley-Dam** [comment]
The QRCodeScanner class has not been formatted correctly, it's using spaces instead of tabs.

**Comment by Stanley-Dam** [comment]
QRCodeScanner on line 30: You can use ! instead of == false.

**Comment by Stanley-Dam** [comment]
QRCodeScanner on line 32: this entire if statement seems to be redundant, this function does not get executed when _isCamAvailible is false. Also, you should never use return here because it disrupts the flow of your code.

**Comment by Stanley-Dam** [comment]
QRCodeScanner on line 35: Redundant casts to float.

**Comment by Stanley-Dam** [comment]
QRCodeScanner on line 51: use else instead of return

**Comment by Stanley-Dam** [comment]
QRCodeScanner on line 43 & 89: Don't add functions to buttons, instead hook them into the button press events in the Awake, these functions should then also be private.

**Comment by Stanley-Dam** [comment]
QRCodeScanner on line 80 & 85: The user won't have any idea that the camera is not working and might think that their application is crashing.

**Comment by Stanley-Dam** [comment]
QRCodeScanner on line 27 & 42: Should be summeries.

**Pull request merged**
